/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tohee
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CalculateButton = new javax.swing.JButton();
        TaxesLabel = new javax.swing.JLabel();
        SubtotalLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ItemPanel1 = new javax.swing.JPanel();
        ItemIcon1 = new javax.swing.JLabel();
        ItemQtyDecreaseButton1 = new javax.swing.JButton();
        ItemQtyIncreaseButton1 = new javax.swing.JButton();
        ItemQuantity1 = new javax.swing.JLabel();
        ItemPrice1 = new javax.swing.JLabel();
        ItemName1 = new javax.swing.JLabel();
        ItemPanel2 = new javax.swing.JPanel();
        ItemIcon2 = new javax.swing.JLabel();
        ItemQtyDecreaseButton2 = new javax.swing.JButton();
        ItemQtyIncreaseButton2 = new javax.swing.JButton();
        ItemQuantity2 = new javax.swing.JLabel();
        ItemPrice2 = new javax.swing.JLabel();
        ItemName2 = new javax.swing.JLabel();
        ItemPanel3 = new javax.swing.JPanel();
        ItemIcon3 = new javax.swing.JLabel();
        ItemQtyDecreaseButton3 = new javax.swing.JButton();
        ItemQtyIncreaseButton3 = new javax.swing.JButton();
        ItemQuantity3 = new javax.swing.JLabel();
        ItemPrice3 = new javax.swing.JLabel();
        ItemName3 = new javax.swing.JLabel();
        ItemPanel4 = new javax.swing.JPanel();
        ItemIcon4 = new javax.swing.JLabel();
        ItemQtyDecreaseButton4 = new javax.swing.JButton();
        ItemQtyIncreaseButton4 = new javax.swing.JButton();
        ItemQuantity4 = new javax.swing.JLabel();
        ItemPrice4 = new javax.swing.JLabel();
        ItemName4 = new javax.swing.JLabel();
        ItemPanel5 = new javax.swing.JPanel();
        ItemIcon5 = new javax.swing.JLabel();
        ItemQtyDecreaseButton5 = new javax.swing.JButton();
        ItemQtyIncreaseButton5 = new javax.swing.JButton();
        ItemQuantity5 = new javax.swing.JLabel();
        ItemPrice5 = new javax.swing.JLabel();
        ItemName5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel1.setText("Shopping Cart");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Items");

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setForeground(new java.awt.Color(50, 50, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Summary");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subtotal");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Taxes");

        CalculateButton.setBackground(new java.awt.Color(20, 20, 20));
        CalculateButton.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(255, 255, 255));
        CalculateButton.setText("CALCULATE");
        CalculateButton.setToolTipText("");
        CalculateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CalculateButton.setBorderPainted(false);
        CalculateButton.setFocusable(false);
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        TaxesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TaxesLabel.setForeground(new java.awt.Color(0, 0, 0));
        TaxesLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TaxesLabel.setText("$0");

        SubtotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubtotalLabel.setForeground(new java.awt.Color(0, 0, 0));
        SubtotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SubtotalLabel.setText("$0");

        TotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TotalLabel.setText("$0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(TaxesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CalculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SubtotalLabel))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TaxesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TotalLabel))
                .addGap(22, 22, 22))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Price");

        ItemPanel1.setPreferredSize(new java.awt.Dimension(100, 70));

        ItemIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/497718-341920643 (1).png"))); // NOI18N
        ItemIcon1.setText("jLabel12");

        ItemQtyDecreaseButton1.setText("-");
        ItemQtyDecreaseButton1.setBorderPainted(false);
        ItemQtyDecreaseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyDecreaseButton1ActionPerformed(evt);
            }
        });

        ItemQtyIncreaseButton1.setText("+");
        ItemQtyIncreaseButton1.setBorderPainted(false);
        ItemQtyIncreaseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyIncreaseButton1ActionPerformed(evt);
            }
        });

        ItemQuantity1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemQuantity1.setText("1");

        ItemPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ItemPrice1.setText("$25.99");

        ItemName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemName1.setText("Forever Aloe Vera Gel");

        javax.swing.GroupLayout ItemPanel1Layout = new javax.swing.GroupLayout(ItemPanel1);
        ItemPanel1.setLayout(ItemPanel1Layout);
        ItemPanel1Layout.setHorizontalGroup(
            ItemPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel1Layout.createSequentialGroup()
                .addComponent(ItemIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(ItemQtyDecreaseButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQtyIncreaseButton1)
                .addGap(71, 71, 71)
                .addComponent(ItemPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(ItemPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemPanel1Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ItemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );
        ItemPanel1Layout.setVerticalGroup(
            ItemPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel1Layout.createSequentialGroup()
                .addGroup(ItemPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIcon1)
                    .addComponent(ItemQtyDecreaseButton1)
                    .addComponent(ItemQtyIncreaseButton1)
                    .addComponent(ItemQuantity1)
                    .addComponent(ItemPrice1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ItemPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ItemName1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        ItemPanel2.setPreferredSize(new java.awt.Dimension(100, 70));

        ItemIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Soothing-Cleanser-3606000463660-SkinCeuticals__1_-removebg-preview.png"))); // NOI18N
        ItemIcon2.setText("jLabel12");

        ItemQtyDecreaseButton2.setText("-");
        ItemQtyDecreaseButton2.setBorderPainted(false);
        ItemQtyDecreaseButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyDecreaseButton2ActionPerformed(evt);
            }
        });

        ItemQtyIncreaseButton2.setText("+");
        ItemQtyIncreaseButton2.setBorderPainted(false);
        ItemQtyIncreaseButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyIncreaseButton2ActionPerformed(evt);
            }
        });

        ItemQuantity2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemQuantity2.setText("1");

        ItemPrice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ItemPrice2.setText("$55.00");

        ItemName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemName2.setText("SkinCeuticals Soothing Cleanser");

        javax.swing.GroupLayout ItemPanel2Layout = new javax.swing.GroupLayout(ItemPanel2);
        ItemPanel2.setLayout(ItemPanel2Layout);
        ItemPanel2Layout.setHorizontalGroup(
            ItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel2Layout.createSequentialGroup()
                .addComponent(ItemIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(ItemQtyDecreaseButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQtyIncreaseButton2)
                .addGap(71, 71, 71)
                .addComponent(ItemPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(ItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemPanel2Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ItemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );
        ItemPanel2Layout.setVerticalGroup(
            ItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel2Layout.createSequentialGroup()
                .addGroup(ItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIcon2)
                    .addComponent(ItemQtyDecreaseButton2)
                    .addComponent(ItemQtyIncreaseButton2)
                    .addComponent(ItemQuantity2)
                    .addComponent(ItemPrice2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ItemName2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        ItemPanel3.setPreferredSize(new java.awt.Dimension(100, 70));

        ItemIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d8d37cd2-a317-4e9f-b26f-3cc246bbca5a_1.63d3f3502f700a540ca70668ec1e3c76-2390733872-removebg-preview (1).png"))); // NOI18N
        ItemIcon3.setText("jLabel12");

        ItemQtyDecreaseButton3.setText("-");
        ItemQtyDecreaseButton3.setBorderPainted(false);
        ItemQtyDecreaseButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyDecreaseButton3ActionPerformed(evt);
            }
        });

        ItemQtyIncreaseButton3.setText("+");
        ItemQtyIncreaseButton3.setBorderPainted(false);
        ItemQtyIncreaseButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyIncreaseButton3ActionPerformed(evt);
            }
        });

        ItemQuantity3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemQuantity3.setText("1");

        ItemPrice3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ItemPrice3.setText("$6.97");

        ItemName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemName3.setText("Head And Shoulders Shampoo");

        javax.swing.GroupLayout ItemPanel3Layout = new javax.swing.GroupLayout(ItemPanel3);
        ItemPanel3.setLayout(ItemPanel3Layout);
        ItemPanel3Layout.setHorizontalGroup(
            ItemPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel3Layout.createSequentialGroup()
                .addComponent(ItemIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(ItemQtyDecreaseButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQtyIncreaseButton3)
                .addGap(71, 71, 71)
                .addComponent(ItemPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(ItemPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemPanel3Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ItemName3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );
        ItemPanel3Layout.setVerticalGroup(
            ItemPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel3Layout.createSequentialGroup()
                .addGroup(ItemPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIcon3)
                    .addComponent(ItemQtyDecreaseButton3)
                    .addComponent(ItemQtyIncreaseButton3)
                    .addComponent(ItemQuantity3)
                    .addComponent(ItemPrice3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ItemPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ItemName3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        ItemPanel4.setPreferredSize(new java.awt.Dimension(100, 70));

        ItemIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thayers-alcohol-free-rose-petal-witch-hazel-facial-toner-49870914-removebg-preview (1).png"))); // NOI18N
        ItemIcon4.setText("jLabel12");

        ItemQtyDecreaseButton4.setText("-");
        ItemQtyDecreaseButton4.setBorderPainted(false);
        ItemQtyDecreaseButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyDecreaseButton4ActionPerformed(evt);
            }
        });

        ItemQtyIncreaseButton4.setText("+");
        ItemQtyIncreaseButton4.setBorderPainted(false);
        ItemQtyIncreaseButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyIncreaseButton4ActionPerformed(evt);
            }
        });

        ItemQuantity4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemQuantity4.setText("1");

        ItemPrice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ItemPrice4.setText("$10.95");

        ItemName4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ItemName4.setText("Thayers Alcohol-Free Witch Hazel Facial Toner");

        javax.swing.GroupLayout ItemPanel4Layout = new javax.swing.GroupLayout(ItemPanel4);
        ItemPanel4.setLayout(ItemPanel4Layout);
        ItemPanel4Layout.setHorizontalGroup(
            ItemPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel4Layout.createSequentialGroup()
                .addComponent(ItemIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(ItemQtyDecreaseButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQuantity4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQtyIncreaseButton4)
                .addGap(71, 71, 71)
                .addComponent(ItemPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(ItemPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemPanel4Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ItemName4)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );
        ItemPanel4Layout.setVerticalGroup(
            ItemPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel4Layout.createSequentialGroup()
                .addGroup(ItemPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIcon4)
                    .addComponent(ItemQtyDecreaseButton4)
                    .addComponent(ItemQtyIncreaseButton4)
                    .addComponent(ItemQuantity4)
                    .addComponent(ItemPrice4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ItemPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ItemName4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        ItemPanel5.setPreferredSize(new java.awt.Dimension(100, 70));

        ItemIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/094d2441-ab91-4030-85cb-7049c4b1026c.b0db4b18af0aafb85b9ecb2dd0189e50-1510936040-removebg-preview (1).png"))); // NOI18N
        ItemIcon5.setText("jLabel12");

        ItemQtyDecreaseButton5.setText("-");
        ItemQtyDecreaseButton5.setBorderPainted(false);
        ItemQtyDecreaseButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyDecreaseButton5ActionPerformed(evt);
            }
        });

        ItemQtyIncreaseButton5.setText("+");
        ItemQtyIncreaseButton5.setBorderPainted(false);
        ItemQtyIncreaseButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQtyIncreaseButton5ActionPerformed(evt);
            }
        });

        ItemQuantity5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemQuantity5.setText("1");

        ItemPrice5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ItemPrice5.setText("$209.99");

        ItemName5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemName5.setText("Oral-B Genius X 10000 Toothbrush");

        javax.swing.GroupLayout ItemPanel5Layout = new javax.swing.GroupLayout(ItemPanel5);
        ItemPanel5.setLayout(ItemPanel5Layout);
        ItemPanel5Layout.setHorizontalGroup(
            ItemPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel5Layout.createSequentialGroup()
                .addComponent(ItemIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(ItemQtyDecreaseButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQuantity5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemQtyIncreaseButton5)
                .addGap(71, 71, 71)
                .addComponent(ItemPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(ItemPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemPanel5Layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(ItemName5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );
        ItemPanel5Layout.setVerticalGroup(
            ItemPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanel5Layout.createSequentialGroup()
                .addGroup(ItemPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemIcon5)
                    .addComponent(ItemQtyDecreaseButton5)
                    .addComponent(ItemQtyIncreaseButton5)
                    .addComponent(ItemQuantity5)
                    .addComponent(ItemPrice5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ItemPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ItemName5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel10)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addComponent(ItemPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void increaseQuantity(javax.swing.JLabel itemQuantityLabel) {
        int quantity = Integer.parseInt(itemQuantityLabel.getText());
        quantity++;
        itemQuantityLabel.setText(String.valueOf(quantity));
    }
    
    private void decreaseQuantity(javax.swing.JLabel itemQuantityLabel) {
        int quantity = Integer.parseInt(itemQuantityLabel.getText());
        if (quantity == 0) return;
        
        quantity--;
        itemQuantityLabel.setText(String.valueOf(quantity));
    }
    
    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        final double ITEM1_COST = 25.99;
        final double ITEM2_COST = 55.00;
        final double ITEM3_COST = 6.97;
        final double ITEM4_COST = 10.95;
        final double ITEM5_COST = 209.99;
        
        final double ITEM1_TOTAL = Integer.parseInt(ItemQuantity1.getText()) * ITEM1_COST;
        final double ITEM2_TOTAL = Integer.parseInt(ItemQuantity2.getText()) * ITEM2_COST;
        final double ITEM3_TOTAL = Integer.parseInt(ItemQuantity3.getText()) * ITEM3_COST;
        final double ITEM4_TOTAL = Integer.parseInt(ItemQuantity4.getText()) * ITEM4_COST;
        final double ITEM5_TOTAL = Integer.parseInt(ItemQuantity5.getText()) * ITEM5_COST;
        
        double subtotal = ITEM1_TOTAL + ITEM2_TOTAL + ITEM3_TOTAL + ITEM4_TOTAL + ITEM5_TOTAL;
        final double taxes = subtotal * 0.13;
        
        
        SubtotalLabel.setText("$" + String.valueOf(subtotal));
        TaxesLabel.setText("$" + String.valueOf(taxes));

        
        TotalLabel.setText("$" + String.valueOf(taxes + subtotal));
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void ItemQtyDecreaseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyDecreaseButton1ActionPerformed
        decreaseQuantity(ItemQuantity1);
    }//GEN-LAST:event_ItemQtyDecreaseButton1ActionPerformed

    private void ItemQtyDecreaseButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyDecreaseButton2ActionPerformed
        decreaseQuantity(ItemQuantity2);

    }//GEN-LAST:event_ItemQtyDecreaseButton2ActionPerformed

    private void ItemQtyDecreaseButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyDecreaseButton3ActionPerformed
        decreaseQuantity(ItemQuantity3);

    }//GEN-LAST:event_ItemQtyDecreaseButton3ActionPerformed

    private void ItemQtyDecreaseButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyDecreaseButton4ActionPerformed
        decreaseQuantity(ItemQuantity4);

    }//GEN-LAST:event_ItemQtyDecreaseButton4ActionPerformed

    private void ItemQtyDecreaseButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyDecreaseButton5ActionPerformed
        decreaseQuantity(ItemQuantity5);
    }//GEN-LAST:event_ItemQtyDecreaseButton5ActionPerformed

    private void ItemQtyIncreaseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyIncreaseButton1ActionPerformed
        increaseQuantity(ItemQuantity1);
    }//GEN-LAST:event_ItemQtyIncreaseButton1ActionPerformed

    private void ItemQtyIncreaseButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyIncreaseButton2ActionPerformed
        increaseQuantity(ItemQuantity2);
    }//GEN-LAST:event_ItemQtyIncreaseButton2ActionPerformed

    private void ItemQtyIncreaseButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyIncreaseButton3ActionPerformed
        increaseQuantity(ItemQuantity3);
    }//GEN-LAST:event_ItemQtyIncreaseButton3ActionPerformed

    private void ItemQtyIncreaseButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyIncreaseButton4ActionPerformed
        increaseQuantity(ItemQuantity4);
    }//GEN-LAST:event_ItemQtyIncreaseButton4ActionPerformed

    private void ItemQtyIncreaseButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQtyIncreaseButton5ActionPerformed
        increaseQuantity(ItemQuantity5);
    }//GEN-LAST:event_ItemQtyIncreaseButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel ItemIcon1;
    private javax.swing.JLabel ItemIcon2;
    private javax.swing.JLabel ItemIcon3;
    private javax.swing.JLabel ItemIcon4;
    private javax.swing.JLabel ItemIcon5;
    private javax.swing.JLabel ItemName1;
    private javax.swing.JLabel ItemName2;
    private javax.swing.JLabel ItemName3;
    private javax.swing.JLabel ItemName4;
    private javax.swing.JLabel ItemName5;
    private javax.swing.JPanel ItemPanel1;
    private javax.swing.JPanel ItemPanel2;
    private javax.swing.JPanel ItemPanel3;
    private javax.swing.JPanel ItemPanel4;
    private javax.swing.JPanel ItemPanel5;
    private javax.swing.JLabel ItemPrice1;
    private javax.swing.JLabel ItemPrice2;
    private javax.swing.JLabel ItemPrice3;
    private javax.swing.JLabel ItemPrice4;
    private javax.swing.JLabel ItemPrice5;
    private javax.swing.JButton ItemQtyDecreaseButton1;
    private javax.swing.JButton ItemQtyDecreaseButton2;
    private javax.swing.JButton ItemQtyDecreaseButton3;
    private javax.swing.JButton ItemQtyDecreaseButton4;
    private javax.swing.JButton ItemQtyDecreaseButton5;
    private javax.swing.JButton ItemQtyIncreaseButton1;
    private javax.swing.JButton ItemQtyIncreaseButton2;
    private javax.swing.JButton ItemQtyIncreaseButton3;
    private javax.swing.JButton ItemQtyIncreaseButton4;
    private javax.swing.JButton ItemQtyIncreaseButton5;
    private javax.swing.JLabel ItemQuantity1;
    private javax.swing.JLabel ItemQuantity2;
    private javax.swing.JLabel ItemQuantity3;
    private javax.swing.JLabel ItemQuantity4;
    private javax.swing.JLabel ItemQuantity5;
    private javax.swing.JLabel SubtotalLabel;
    private javax.swing.JLabel TaxesLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
